# Generated by Django 4.2.7 on 2023-12-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0003_modelreg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelAlex',
        ),
        migrations.DeleteModel(
            name='ModelAlexImg',
        ),
        migrations.AddField(
            model_name='modelreg',
            name='img',
            field=models.ImageField(default='', upload_to='imgs'),
        ),
    ]
