# Generated by Django 4.2.7 on 2023-12-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0004_delete_modelalex_delete_modelaleximg_modelreg_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelreg',
            name='img',
            field=models.FileField(default='', upload_to='imgs'),
        ),
    ]
